# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
aho-corasick-0.6.6
arrayvec-0.4.7
assert_cli-0.6.3
atty-0.2.11
backtrace-0.3.9
backtrace-sys-0.1.24
bitflags-1.0.3
byteorder-1.2.4
cargo_metadata-0.6.0
cc-1.0.18
cfg-if-0.1.5
colored-1.6.1
crossbeam-deque-0.2.0
crossbeam-epoch-0.3.1
crossbeam-utils-0.2.2
derive-new-0.5.5
diff-0.1.11
difference-2.0.0
either-1.5.0
ena-0.9.3
env_logger-0.5.12
environment-0.1.1
error-chain-0.12.0
failure-0.1.2
failure_derive-0.1.2
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
getopts-0.2.18
humantime-1.1.1
isatty-0.1.8
itertools-0.7.8
itoa-0.4.2
lazy_static-1.1.0
libc-0.2.43
log-0.4.4
memchr-2.0.1
memoffset-0.2.1
nodrop-0.1.12
num_cpus-1.8.0
owning_ref-0.3.3
parking_lot-0.5.5
parking_lot_core-0.2.14
proc-macro2-0.4.13
quick-error-1.2.2
quote-0.6.6
rand-0.4.3
redox_syscall-0.1.40
redox_termios-0.1.1
regex-1.0.2
regex-syntax-0.6.2
rustc-ap-arena-237.0.0
rustc-ap-rustc_cratesio_shim-237.0.0
rustc-ap-rustc_data_structures-237.0.0
rustc-ap-rustc_errors-237.0.0
rustc-ap-rustc_target-237.0.0
rustc-ap-serialize-237.0.0
rustc-ap-syntax-237.0.0
rustc-ap-syntax_pos-237.0.0
rustc-demangle-0.1.9
rustc-hash-1.0.1
rustc-rayon-0.1.1
rustc-rayon-core-0.1.1
rustfmt-nightly-0.99.4
ryu-0.2.4
scoped-tls-0.1.2
scopeguard-0.3.3
semver-0.9.0
semver-parser-0.7.0
serde-1.0.71
serde_derive-1.0.71
serde_json-1.0.26
smallvec-0.6.5
stable_deref_trait-1.1.1
syn-0.14.8
synstructure-0.9.0
term-0.5.1
termcolor-0.3.6
termcolor-1.0.1
termion-1.5.1
thread_local-0.3.6
toml-0.4.6
ucd-util-0.1.1
unicode-segmentation-1.2.1
unicode-width-0.1.5
unicode-xid-0.1.0
unreachable-1.0.0
utf8-ranges-1.0.0
version_check-0.1.4
void-1.0.2
winapi-0.3.5
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
wincolor-0.1.6
wincolor-1.0.0
"

inherit cargo

DESCRIPTION="Tool to find and fix Rust formatting issues"
HOMEPAGE="https://github.com/rust-lang-nursery/rustfmt"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="Apache-2.0/MIT" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""
