# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=7

CRATES="
aho-corasick-0.6.8
ansi_term-0.11.0
atty-0.2.11
bitflags-1.0.4
cargo-bloat-0.6.0
cc-1.0.23
cfg-if-0.1.5
clap-2.32.0
flate2-1.0.2
goblin-0.0.17
itoa-0.4.2
kernel32-sys-0.2.2
lazy_static-1.1.0
libc-0.2.43
log-0.4.5
memchr-2.0.2
memmap-0.6.2
miniz-sys-0.1.10
multimap-0.4.0
object-0.10.0
plain-0.2.3
proc-macro2-0.4.18
quote-0.6.8
redox_syscall-0.1.40
redox_termios-0.1.1
regex-1.0.5
regex-syntax-0.6.2
rustc-demangle-0.1.9
ryu-0.2.6
scroll-0.9.0
scroll_derive-0.9.4
serde-1.0.77
serde_derive-1.0.77
serde_json-1.0.27
strsim-0.7.0
structopt-0.2.10
structopt-derive-0.2.10
syn-0.14.9
syn-0.15.1
term_size-0.3.1
termion-1.5.1
textwrap-0.10.0
thread_local-0.3.6
ucd-util-0.1.1
unicode-width-0.1.5
unicode-xid-0.1.0
utf8-ranges-1.0.1
uuid-0.6.5
vec_map-0.8.1
version_check-0.1.4
winapi-0.2.8
winapi-0.3.5
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Find out what takes most of the space in your executable."
HOMEPAGE="https://github.com/RazrFalcon/cargo-bloat"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""
