# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
advapi32-sys-0.2.0
aho-corasick-0.6.3
atty-0.2.3
backtrace-0.3.4
backtrace-sys-0.1.16
bitflags-0.7.0
bitflags-0.9.1
cargo-0.22.0
cargo-outdated-0.7.0
cc-1.0.3
cfg-if-0.1.2
cmake-0.1.28
core-foundation-0.4.4
core-foundation-sys-0.4.4
crates-io-0.11.0
crossbeam-0.2.10
curl-0.4.8
curl-sys-0.3.15
dbghelp-sys-0.2.0
docopt-0.8.1
dtoa-0.4.2
env_logger-0.4.3
error-chain-0.11.0
filetime-0.1.14
flate2-0.2.20
fnv-1.0.6
foreign-types-0.2.0
fs2-0.4.2
fuchsia-zircon-0.2.1
fuchsia-zircon-sys-0.2.0
git2-0.6.8
git2-curl-0.7.0
glob-0.2.11
globset-0.2.1
hex-0.2.0
home-0.3.0
idna-0.1.4
ignore-0.2.2
itoa-0.3.4
jobserver-0.1.8
kernel32-sys-0.2.2
lazy_static-0.2.11
libc-0.2.33
libgit2-sys-0.6.16
libssh2-sys-0.2.6
libz-sys-1.0.18
log-0.3.8
matches-0.1.6
memchr-1.0.2
memchr-2.0.0
miniz-sys-0.1.10
miow-0.2.1
net2-0.2.31
num-traits-0.1.40
num_cpus-1.7.0
openssl-0.9.21
openssl-probe-0.1.1
openssl-sys-0.9.21
percent-encoding-1.0.1
pkg-config-0.3.9
psapi-sys-0.1.0
quote-0.3.15
rand-0.3.18
redox_syscall-0.1.31
redox_termios-0.1.1
regex-0.2.2
regex-syntax-0.4.1
rustc-demangle-0.1.5
same-file-0.1.3
scoped-tls-0.1.0
scopeguard-0.1.2
semver-0.7.0
semver-parser-0.7.0
serde-1.0.21
serde_derive-1.0.21
serde_derive_internals-0.17.0
serde_ignored-0.0.3
serde_json-1.0.6
shell-escape-0.1.3
socket2-0.2.4
strsim-0.6.0
syn-0.11.11
synom-0.11.3
tabwriter-1.0.3
tar-0.4.13
tempdir-0.3.5
termcolor-0.3.3
termion-1.5.1
thread_local-0.3.4
toml-0.4.5
unicode-bidi-0.3.4
unicode-normalization-0.1.5
unicode-width-0.1.4
unicode-xid-0.0.4
unreachable-1.0.0
url-1.6.0
userenv-sys-0.2.0
utf8-ranges-1.0.0
vcpkg-0.2.2
void-1.0.2
walkdir-1.0.7
winapi-0.2.8
winapi-build-0.1.1
wincolor-0.1.4
ws2_32-sys-0.2.1
"

inherit cargo

DESCRIPTION="Cargo subcommand for displaying when dependencies are out of date"
HOMEPAGE="https://github.com/kbknapp/cargo-outdated.git"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""
