# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
aho-corasick-0.7.6
ansi_term-0.11.0
assert_cmd-1.0.1
atty-0.2.11
autocfg-0.1.7
bitflags-1.2.1
bstr-0.2.8
cargo-watch-7.5.0
cc-1.0.47
cfg-if-0.1.10
chrono-0.4.11
clap-2.33.1
console-0.11.3
darling-0.10.2
darling_core-0.10.2
darling_macro-0.10.2
derive_builder-0.9.0
derive_builder_core-0.9.0
difference-2.0.0
doc-comment-0.3.3
dtoa-0.4.4
encode_unicode-0.3.6
env_logger-0.7.1
filetime-0.2.8
float-cmp-0.6.0
fnv-1.0.6
fsevent-0.4.0
fsevent-sys-2.0.1
fuchsia-zircon-0.3.3
fuchsia-zircon-sys-0.3.3
glob-0.3.0
globset-0.4.5
ident_case-1.0.1
inotify-0.7.0
inotify-sys-0.1.3
insta-0.16.1
iovec-0.1.4
itoa-0.4.4
kernel32-sys-0.2.2
lazy_static-0.2.11
lazy_static-1.4.0
lazycell-1.2.1
libc-0.2.65
linked-hash-map-0.5.2
log-0.4.8
memchr-2.2.1
mio-0.6.19
mio-extras-2.0.5
miow-0.2.1
net2-0.2.33
nix-0.17.0
normalize-line-endings-0.3.0
notify-4.0.15
num-integer-0.1.41
num-traits-0.2.9
numtoa-0.1.0
predicates-1.0.4
predicates-core-1.0.0
predicates-tree-1.0.0
proc-macro2-1.0.6
quote-1.0.2
redox_syscall-0.1.56
redox_termios-0.1.1
regex-1.3.9
regex-syntax-0.6.18
ryu-1.0.2
same-file-1.0.5
serde-1.0.102
serde_derive-1.0.102
serde_json-1.0.41
serde_yaml-0.8.11
slab-0.4.2
stderrlog-0.4.3
strsim-0.8.0
strsim-0.9.2
syn-1.0.8
term_size-0.3.1
termcolor-1.0.5
terminal_size-0.1.13
termion-1.5.5
termios-0.3.1
textwrap-0.11.0
thread_local-0.3.4
thread_local-1.0.1
time-0.1.42
treeline-0.1.0
unicode-width-0.1.6
unicode-xid-0.2.0
unreachable-1.0.0
vec_map-0.8.1
void-1.0.2
wait-timeout-0.2.0
walkdir-2.3.1
watchexec-1.14.0
winapi-0.2.8
winapi-0.3.9
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.2
winapi-x86_64-pc-windows-gnu-0.4.0
wincolor-1.0.3
ws2_32-sys-0.2.1
yaml-rust-0.4.3
"

inherit cargo

DESCRIPTION="Watches over your Cargo project’s source"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/passcod/cargo-watch"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 BSD-3-Clause BSL-1.0 CC0-1.0 ISC MIT Unlicense"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""
