# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
ansi_term-0.11.0
arrayref-0.3.5
atty-0.2.11
backtrace-0.3.9
backtrace-sys-0.1.24
bitflags-1.0.4
block-buffer-0.3.3
byte-tools-0.2.0
byteorder-1.2.7
cargo-call-stack-0.1.0
cargo-project-0.1.0
cargo-project-0.2.1
cc-1.0.25
cfg-if-0.1.6
clap-2.32.0
digest-0.7.6
either-1.5.0
failure-0.1.3
failure_derive-0.1.3
fake-simd-0.1.2
fixedbitset-0.1.9
generic-array-0.9.0
leb128-0.2.3
libc-0.2.44
maplit-1.0.1
ordermap-0.3.5
pest-2.0.2
pest_derive-2.0.1
pest_generator-2.0.0
pest_meta-2.0.3
petgraph-0.4.13
proc-macro2-0.4.24
quote-0.6.10
redox_syscall-0.1.43
redox_termios-0.1.1
rustc-cfg-0.4.0
rustc-demangle-0.1.9
rustc_version-0.2.3
semver-0.9.0
semver-parser-0.7.0
serde-1.0.81
serde_derive-1.0.81
sha-1-0.7.0
stack-sizes-0.2.0
strsim-0.7.0
syn-0.14.9
syn-0.15.22
synstructure-0.10.1
termion-1.5.1
textwrap-0.10.0
toml-0.4.10
typenum-1.10.0
ucd-trie-0.1.1
unicode-width-0.1.5
unicode-xid-0.1.0
vec_map-0.8.1
winapi-0.3.6
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
xmas-elf-0.6.2
zero-0.1.2
"

inherit cargo

DESCRIPTION="Whole program static stack analysis"
HOMEPAGE="https://github.com/japaric/cargo-call-stack"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT OR Apache-2.0" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""

cargo_src_install() {
	cargo install -j $(makeopts_jobs) --path="${S}" --root="${D}/usr" $(usex debug --debug "") \
		|| die "cargo install failed"
	rm -f "${D}/usr/.crates.toml"

	[ -d "${S}/man" ] && doman "${S}/man" || return 0
}

