# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	adler2@2.0.1
	aho-corasick@1.1.3
	anyhow@1.0.98
	ar@0.9.0
	autocfg@1.5.0
	bpaf@0.9.20
	bpaf_derive@0.5.17
	camino@1.1.11
	capstone-sys@0.17.0
	capstone@0.13.0
	cargo-platform@0.2.0
	cargo-show-asm@0.2.52
	cargo-util-schemas@0.8.2
	cargo_metadata@0.21.0
	cc@1.2.32
	cfg-if@1.0.1
	crc32fast@1.5.0
	displaydoc@0.2.5
	equivalent@1.0.2
	erased-serde@0.4.6
	flate2@1.1.2
	form_urlencoded@1.2.1
	hashbrown@0.15.5
	hermit-abi@0.5.2
	icu_collections@2.0.0
	icu_locale_core@2.0.0
	icu_normalizer@2.0.0
	icu_normalizer_data@2.0.0
	icu_properties@2.0.1
	icu_properties_data@2.0.1
	icu_provider@2.0.0
	idna@1.0.3
	idna_adapter@1.2.1
	indexmap@2.10.0
	is-terminal@0.4.16
	is_ci@1.2.0
	itoa@1.0.15
	libc@0.2.174
	line-span@0.1.5
	litemap@0.8.0
	memchr@2.7.5
	miniz_oxide@0.8.9
	nom@8.0.0
	num-traits@0.2.19
	object@0.37.2
	ordered-float@2.10.1
	owo-colors@4.2.2
	percent-encoding@2.3.1
	potential_utf@0.1.2
	proc-macro2@1.0.95
	quote@1.0.40
	regex-automata@0.4.9
	regex-syntax@0.8.5
	regex@1.11.1
	rustc-demangle@0.1.26
	ruzstd@0.8.1
	ryu@1.0.20
	same-file@1.0.6
	semver@1.0.26
	serde-untagged@0.1.7
	serde-value@0.7.0
	serde@1.0.219
	serde_derive@1.0.219
	serde_json@1.0.142
	serde_spanned@0.6.9
	shlex@1.3.0
	smallvec@1.15.1
	stable_deref_trait@1.2.0
	supports-color@2.1.0
	supports-color@3.0.2
	syn@2.0.104
	synstructure@0.13.2
	thiserror-impl@2.0.12
	thiserror@2.0.12
	tinystr@0.8.1
	toml@0.8.23
	toml_datetime@0.6.11
	toml_edit@0.22.27
	toml_write@0.1.2
	twox-hash@2.1.1
	typeid@1.0.3
	unicode-ident@1.0.18
	unicode-xid@0.2.6
	url@2.5.4
	utf8_iter@1.0.4
	winapi-util@0.1.9
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	winnow@0.7.12
	writeable@0.6.1
	yoke-derive@0.8.0
	yoke@0.8.0
	zerofrom-derive@0.1.6
	zerofrom@0.1.6
	zerotrie@0.2.2
	zerovec-derive@0.11.1
	zerovec@0.11.4
"

inherit cargo

DESCRIPTION="A cargo subcommand that displays the generated assembly of Rust source code."
HOMEPAGE="https://github.com/pacak/cargo-show-asm"
SRC_URI="
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" Apache-2.0 ISC MIT Unicode-3.0"
SLOT="0"
KEYWORDS="amd64"
