# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.2-alpha.0

EAPI=7

CRATES="
adler-1.0.2
aho-corasick-0.7.18
ansi_term-0.12.1
anyhow-1.0.43
argh-0.1.6
argh_derive-0.1.6
argh_shared-0.1.6
ascii_table-3.0.2
atty-0.2.14
autocfg-1.0.1
bitflags-1.3.2
bstr-0.2.16
byte-unit-4.0.12
byteorder-1.4.3
bytes-1.1.0
bytesize-1.1.0
cargo-diet-1.2.3
cfg-if-1.0.0
chrono-0.4.19
combine-4.6.1
crc32fast-1.2.1
criner-waste-report-0.1.4
difference-2.0.0
filetime-0.2.15
flate2-1.0.21
fnv-1.0.7
globset-0.4.8
heck-0.3.3
hermit-abi-0.1.19
json-0.12.4
kernel32-sys-0.2.2
lazy_static-1.4.0
libc-0.2.101
linked-hash-map-0.5.4
locate-cargo-manifest-0.2.2
log-0.4.14
memchr-2.4.1
miniz_oxide-0.4.4
num-integer-0.1.44
num-traits-0.2.14
numtoa-0.1.0
proc-macro2-1.0.29
quick-error-2.0.1
quote-1.0.9
redox_syscall-0.2.10
redox_termios-0.1.2
regex-1.5.4
regex-syntax-0.6.25
rmp-0.8.10
rmp-serde-0.15.5
serde-1.0.130
serde_derive-1.0.130
syn-1.0.76
tar-0.4.37
termion-1.5.6
termsize-0.1.6
time-0.1.44
toml-0.5.8
toml_edit-0.2.1
unicode-segmentation-1.8.0
unicode-xid-0.2.2
utf8-width-0.1.5
wasi-0.10.0+wasi-snapshot-preview1
winapi-0.2.8
winapi-0.3.9
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
xattr-0.2.2
"

inherit cargo

DESCRIPTION="Make your crate lean by computing size-optimal include directives for Cargo manifests"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/the-lean-crate/cargo-diet"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 Apache-2.0 WITH LLVM-exception BSD-3-Clause MIT Unlicense Zlib"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""
