# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.2-alpha.0

EAPI=7

CRATES="
adler-0.2.3
aho-corasick-0.7.13
ansi_term-0.12.1
anyhow-1.0.32
argh-0.1.3
argh_derive-0.1.1
argh_shared-0.1.1
ascii-0.9.3
ascii_table-3.0.1
atty-0.2.14
autocfg-1.0.0
bstr-0.2.13
byte-unit-3.1.4
byteorder-1.3.4
bytesize-1.0.1
cargo-diet-1.2.0
cfg-if-0.1.10
chrono-0.4.13
combine-3.8.1
crc32fast-1.2.0
criner-waste-report-0.1.4
difference-2.0.0
either-1.5.3
filetime-0.2.10
flate2-1.0.16
fnv-1.0.7
globset-0.4.5
heck-0.3.1
hermit-abi-0.1.15
json-0.12.4
kernel32-sys-0.2.2
lazy_static-1.4.0
libc-0.2.73
linked-hash-map-0.5.3
locate-cargo-manifest-0.2.0
log-0.4.11
memchr-2.3.3
miniz_oxide-0.4.0
num-integer-0.1.43
num-traits-0.2.12
numtoa-0.1.0
proc-macro2-1.0.19
quick-error-1.2.3
quote-1.0.7
redox_syscall-0.1.57
redox_termios-0.1.1
regex-1.3.9
regex-syntax-0.6.18
rmp-0.8.9
rmp-serde-0.14.4
serde-1.0.114
serde_derive-1.0.114
syn-1.0.35
tar-0.4.29
termion-1.5.5
termsize-0.1.6
thiserror-1.0.20
thiserror-impl-1.0.20
thread_local-1.0.1
time-0.1.43
toml-0.5.6
toml_edit-0.2.0
unicode-segmentation-1.6.0
unicode-xid-0.2.1
unreachable-1.0.0
void-1.0.2
winapi-0.2.8
winapi-0.3.9
winapi-build-0.1.1
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
xattr-0.2.2
"

inherit cargo

DESCRIPTION="Make your crate lean by computing size-optimal include directives for Cargo manifests"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/the-lean-crate/cargo-diet"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 BSD-3-Clause GPL-3.0+ MIT Unlicense"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=""
RDEPEND=""
